# Generated by Django 2.1b1 on 2018-12-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbfilkom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koleksi',
            name='topik_koleksi',
        ),
        migrations.AddField(
            model_name='koleksi',
            name='topik_koleksi',
            field=models.ManyToManyField(to='rbfilkom.TopikKoleksi'),
        ),
    ]
