# Generated by Django 2.1b1 on 2018-12-13 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbfilkom', '0002_auto_20181213_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koleksi',
            name='topik_koleksi',
        ),
        migrations.AddField(
            model_name='koleksi',
            name='topik_koleksi',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='rbfilkom.TopikKoleksi'),
            preserve_default=False,
        ),
    ]
