# Generated by Django 2.1b1 on 2019-02-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbfilkom', '0004_skripsi_abstrak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koleksi',
            name='gambar',
            field=models.ImageField(blank=True, default='static/img/empty.png', null=True, upload_to='files/', verbose_name='Image'),
        ),
    ]
