# Generated by Django 2.1b1 on 2019-02-09 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbfilkom', '0005_auto_20190205_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='has', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
