# Generated by Django 2.1b1 on 2019-02-09 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbfilkom', '0007_notifikasi_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifikasi',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get', to='rbfilkom.Mahasiswa'),
        ),
    ]
