# Generated by Django 2.1b1 on 2019-02-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbfilkom', '0008_auto_20190209_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifikasi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
