# Generated by Django 2.1b1 on 2019-02-09 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbfilkom', '0009_auto_20190209_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifikasi',
            name='kode_pesan',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='rbfilkom.TransaksiPemesanan'),
        ),
        migrations.AddField(
            model_name='notifikasi',
            name='kode_pinjam',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='rbfilkom.TransaksiPeminjaman'),
        ),
    ]
