# Generated by Django 2.1b1 on 2019-02-09 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbfilkom', '0010_auto_20190209_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifikasi',
            name='kode_pesan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='rbfilkom.TransaksiPemesanan'),
        ),
    ]
