# Generated by Django 2.1b1 on 2019-02-09 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbfilkom', '0011_auto_20190209_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifikasi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get', to='rbfilkom.Mahasiswa'),
        ),
    ]
