# Generated by Django 2.1b1 on 2019-02-10 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbfilkom', '0013_auto_20190210_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_denda', models.CharField(max_length=100)),
                ('kode_transaksi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='has', to='rbfilkom.TransaksiPeminjaman')),
            ],
        ),
    ]
