# Generated by Django 2.1b1 on 2019-02-10 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbfilkom', '0014_denda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, default='-', max_length=200)),
                ('kode_pesan', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='give', to='rbfilkom.TransaksiPemesanan')),
                ('kode_pinjam', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='give', to='rbfilkom.TransaksiPeminjaman')),
            ],
        ),
    ]
