# Generated by Django 2.1b1 on 2019-02-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbfilkom', '0015_feedbacks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedbacks',
            new_name='Feedback',
        ),
    ]
