# Generated by Django 2.1b1 on 2019-02-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbfilkom', '0017_feedback_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahasiswa',
            old_name='password',
            new_name='Angkatan',
        ),
    ]
