# Generated by Django 2.1b1 on 2019-02-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbfilkom', '0018_auto_20190212_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksipemesanan',
            name='antrian',
            field=models.IntegerField(default=0),
        ),
    ]
