# Generated by Django 2.1b1 on 2019-02-22 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbfilkom', '0022_auto_20190218_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksipemesanan',
            name='tenggat_waktu',
            field=models.DateField(default=datetime.datetime(2019, 2, 22, 16, 55, 10, 725278)),
        ),
    ]
