# Generated by Django 2.1b1 on 2019-02-27 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbfilkom', '0024_auto_20190227_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticvariable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaksipemesanan',
            name='tenggat_waktu',
            field=models.DateField(default=datetime.datetime(2019, 2, 27, 20, 34, 24, 240055)),
        ),
    ]
