# Generated by Django 2.1b1 on 2019-02-27 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbfilkom', '0026_auto_20190227_2107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AlterField(
            model_name='transaksipemesanan',
            name='tenggat_waktu',
            field=models.DateField(default=datetime.datetime(2019, 2, 27, 21, 10, 7, 282269)),
        ),
    ]
